

USE codeup_test_db;
DROP TABLE IF EXISTS albums;
CREATE TABLE albums (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    artist VARCHAR(50) NOT NULL DEFAULT 'NONE',
    name VARCHAR(100) NOT NULL DEFAULT 'NONE',
    release_date INT UNSIGNED NOT NULL DEFAULT 0,
    genre VARCHAR(50) NOT NULL DEFAULT 'NONE',
    sales FLOAT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);